name: Build LLVM

on:
  workflow_dispatch:
    inputs:
      gitreletag:
        description: Git Release Tag
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pull main repo
        uses: actions/checkout@v4

      - name: Setup
        run: |
          cmake -Sllvm -Bbuild -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_ENABLE_PROJECTS=mlir -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_INSTALL_PREFIX="./build/.install" -DLLVM_BUILD_TOOLS=OFF -DLLVM_BUILD_TESTS=OFF -DMLIR_INCLUDE_INTEGRATION_TESTS=OFF -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_ENABLE_WARNINGS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_TARGETS_TO_BUILD="SPIRV;AMDGPU"

      - name: Compile
        run: cmake --build "./build/"

      - name: Install
        run: cmake --install "./build/"

      - name: Build archive
        working-directory: ./build/.install/
        run: 7z.exe a -tzip -mx=9 ..\..\release_bin.zip .\*

      - name: Release stuff
        uses: softprops/action-gh-release@v2
        with:
          gitreletag: ${{ inputs.gitreletag }}
          make_latest: true
          token: ${{ secrets.GIT_RELEASE_TOKEN }}
          files: ./release_bin.zip
